name: Build and push to GCP Artifact Registry
on:
  workflow_call:
    secrets:
      GCP_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true

env:
  GCP_KEY: ${{ secrets.GCP_KEY }}
  REGION: europe-west6
  IMG_URL: europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/madebyme-artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        end: [ be ]

    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"
          export_environment_variables: true
          create_credentials_file: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Authenticate Docker
        run: |-
          gcloud --quiet auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.end }}.Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.IMG_URL }}/${{ matrix.end }}:${{ github.sha }}
            ${{ env.IMG_URL }}/${{ matrix.end }}:latest
          cache-from: type=registry,ref=${{ env.IMG_URL }}/${{ matrix.end }}:buildcache
          cache-to: type=registry,ref=${{ env.IMG_URL }}/${{ matrix.end }}:buildcache,mode=max
          secrets: |
            google_credentials=${{ env.GCP_KEY }}
